### ISSUE TITLE
Error about some missing bean.

### ISSUE THREAD

**Issue by Prathemesh** [salisuwy/building-spring-boot-resp-api-v3#1]
I have followed the steps that you have outlined in your tutorial.  However, I get the following error:

```
Application startup failed 

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
```

I asked this question on [StackOverflow](https://stackoverflow.com/questions/49911186/rest-api-queries-return-a-404) and was told about using a Bean [like this](https://github.com/vijayinani/SpringBootForRestApi/blob/master/src/main/java/com/inani/vijay/springbootforrestapi/OracleConfiguration.java).  However, since you have not mentioned in the tutorial, I am not sure if I will actually need it.  

Could you please confirm if a Bean is required at all?  If yes, then were to include that and why?  

P.S.:  The project that I coded is [here](https://github.com/Prathemesh/SpringBoot2).  Also, if you want me to comment on your Medium post as well, then please let me know likewise.  Thanks.

**Comment by salisuwy** [comment]
Bean is not required in this case. But if you have a class that needs to be initialized and managed by the Spring IoC container, then you will have to annotate it with @Bean or in your XML config file.
I've gone through your [code here](https://github.com/Prathemesh/SpringBoot2), everything seems fine. Have you tried "cleaning and rebuilding the app"?

**Comment by Prathemesh** [comment]
Hi @salisuwy, you are right, I didn't need any bean.  I was having issues with my Java version - I was using version 9; while I should have used 8.  So, apparently although everything was correct, I got errors.  It works like a charm with Java 8, though.  

Thanks for your amazing article and help!  Please also feel free to close this issue.

**Comment by salisuwy** [comment]
I'm glad to hear that
